resources:
  repositories:
  - repository: git-experiment
    type: github
    endpoint: github
    name: kcreddyv/git-experiment
    ref: master
  - repository: package
    type: github
    endpoint: github
    name: kcreddyv/package
    ref: master
  - repository: hello-world
    type: github
    endpoint: github
    name: kcreddyv/hello-world
    ref: master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: git-experiment
- checkout: package
- checkout: hello-world
