resources:
  repositories:
  - repository: git-experiment
    type: github
    endpoint: github
    name: kcreddyv/git-experiment
    ref: master
  - repository: package
    type: github
    endpoint: github
    name: kcreddyv/package
    ref: master
  - repository: hello-world
    type: github
    endpoint: github
    name: kcreddyv/hello-world
    ref: master

pool:
  vmImage: 'ubuntu-latest'
  

steps:
- checkout: git-experiment
  persistCredentials: 'true'
- script: |
     echo $(Build.Repository.Name)
     cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
     git tag something
     git push origin something
- checkout: package
  persistCredentials: 'true'
- script: |
     echo $(Build.Repository.Name)
     cd $(Build.SourcesDirectory)/$(Build.Repository.Name)
     git tag something
     git push origin something
- checkout: hello-world
  persistCredentials: 'true'
- script: |
     echo $(Build.Repository.Name)
     cd $(Build.SourcesDirectory)/$(Build.Repository.Name) 
     git tag something
     git push origin something