resources:
  repositories:
  - repository: git-experiment
    type: github
    endpoint: github
    name: kcreddyv/git-experiment
    ref: master
  - repository: package
    type: github
    endpoint: github
    name: kcreddyv/package
    ref: master
  - repository: hello-world
    type: github
    endpoint: github
    name: kcreddyv/hello-world
    ref: master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: git-experiment
  path: git-experiment
- script: |
     dir $(Agent.BuildDirectory)/git-experiment
     git tag something 
     git push something
- checkout: package
  path: package
- script: |
     dir $(Agent.BuildDirectory)/package
     git tag something 
     git push something
- checkout: hello-world
  path: hello-world
- script: |
     dir $(Agent.BuildDirectory)/hello-world
     git tag something 
     git push something