resources:
  repositories:
  - repository: git-experiment
    type: github
    endpoint: github
    name: kcreddyv/git-experiment
    ref: master
  - repository: package
    type: github
    endpoint: github
    name: kcreddyv/package
    ref: master
  - repository: hello-world
    type: github
    endpoint: github
    name: kcreddyv/hello-world
    ref: master

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- checkout: git-experiment
  # path: git-experiment
  persistCredentials: 'true'
- script: |
     cd $(Build.SourcesDirectory)/git-experiment
     git tag something
     git push origin something
- checkout: package
  # path: package
  persistCredentials: 'true'
- script: |
     cd $(Build.SourcesDirectory)/package
     git tag something
     git push origin something
- checkout: hello-world
  # path: hello-world
  persistCredentials: 'true'
- script: |
     cd $(Build.SourcesDirectory)/hello-world 
     git tag something
     git push origin something