resources:
  repositories:
  - repository: git-experiment
    type: github
    name: kcreddyv/git-experiment
    ref: master
    endpoint: https://github.com/
  - repository: package
    type: github
    name: kcreddyv/package
    ref: master
    endpoint: https://github.com/
  - repository: hello-world
    type: github
    name: kcreddyv/hello-world
    ref: master
    endpoint: https://github.com/

steps:
- checkout: git-experiment
- checkout: package
- checkout: hello-world
